### PR TITLE
move "defining information" to introduction

### PR DESCRIPTION
**Pull request by davaya**

### CODE REVIEW

**Comment by dlemire60** [comment]
General: I seem to recall a set of design principles or requirements for JADN in some other documentation. Should that appear somewhere in this section?

Specific comments:
1. In 1.1.1: Only one of the five bullets from RFC 3444 is presented as a quotation but all five appear to be verbatim from that document. I'd suggest removing the quotation marks from the final bullet and adding a parenthetical section reference at the end of each bullet.
2. In 1.1.1: suggest a small addition:  "This allows IMs to model any kind of data, from simple structures such as value ranges or coordinates, to protocol messages, APIs, and method signatures, to complete documents, without the complexity of _also_ modeling programming languages and techniques."
3. In 1.1.1: If the two bullets near the end come from some other source (I don't remember) it should be cited.
4. In 1.1.2: If the suggestion about citing RFC 3444 sections is accepted, apply the same approach here.
5. In 1.1.2: (editorial) first quotation is missing a closing period.
6. In 1.1.2: (editorial) I believe a comma is needed after "environment": "A JADN IM uses UML datatypes to define _data_, not an _environment_ and expresses ..."
7. In 1.1.4: I think it would be helpful for the first sentence describing "lexical values" (or at least its first clause) to appear somewhere earlier in section 1, as the concept of lexical values has already been used several times.
8. In 1.1.4: (editorial) In the key principles, remove the comma in "c) insignificant with respect to, the model."
9. In 1.1.4: (editorial) In the final bullet, remove the comma in "If a logical value can be losslessly converted among multiple lexical values, then its information content is no greater than the smallest of those values."

**Comment by davaya** [comment]
You're probably thinking about the OSIM goals https://github.com/oasis-tcs/osim/blob/main/im-goals.md.  They're very high level and already covered, but the glossaries need to be harmonized, with a few more words here than the OSIM bullets.

All good suggestions; thanks for the careful review.  I think the comma in 8. serves a purpose:

a) consistent with
b) inconsistent with
c) insignificant with respect to

are parallel concepts set off by the comma from "the model".  I'll see if it can be re-written to put model before the alternatives, or distributed across the first two:

" ... any serialized data is a) consistent with the model, b) inconsistent with the model, or c) insignificant."

**Comment by dlemire60** [comment]
Ultimately I'm not that fussed about the comma.  :-)

**Comment by dlemire60** [comment]
Actually, the objectives I was thinking about are already in the CN, in section 3.1. We might want to consider if they should appear earlier but they are present.

**Comment by davaya** [comment]
I added section references to see how they look.  Either way is OK but IMO they are more distracting than helpful.

3, the two bullets are original CN material
7. lexical values are defined in 1.1.3, but I reworded it to make clearer that RDF was the definition, not a reference.

**Pull request merged**
